#!/usr/bin/env python3
'''Tools For Trimming Sequences'''
def sanger_cleanest(min_len = 600,
                    max_len = None,):
    '''Longest Sequence Stretch Without any Ns'''
    print('sanger_cleanest in progress')
def sliding_window(
            sequence = test_sequence(),
            window_size = 20,
            max_number_ns = 2,
            max_ns_inarow = 2,
            min_len = 600,
            max_len = None,):
    '''Sliding Window With Specifications'''
    print('sliding_window in progress')
    print(sequence)
def test_sequence():
    return 'NNNNNNNNGGNNANANTCTGANCNGCCAAGTAGCGTGAAGGATGACTGCCCTATGGGTTGTAAACTTCTTTTATACGGGAATAAAGTTAGCCACGTGTGGCTTTTTGTATGTACCGTATGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGGTTGTTAAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGATACTGGCGACCTTGAGTGCAACAGAGGTAGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCTTACTGGATTGTAACTGACGCTGATGCTCGAAAGTGTGGGTATCAAACAGGATTAGATACCCTGGTAGTCCACACAGTAAACGATGAATACTCGCTGTTGGCGATATACAGTCAGCGGCCAAGCGAAAGCATTAAGTATTCCACCTGGGGAGTACGCCGGCAACGGTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGAGGAACATGTGGTTTAATTCGATGATACGCGAGGAACCTTACCCGGGCTTAAATTGCAACTGACTGAATCGGAAACGGTTCTTTCTTCGGACAGTTGTGAAGGTGCTGCATGGTTGTCGTCAGCTCGTGCCGTGAGGTGTCGGCTTAAGTGCCATAACGAGCGCAACCCTTATCGATAGTTACTAGCAGGTNATGCTGAGGACTCTATCGAGACTGCCGTCGTAAGATGTGAGGAAGGTGGGGATGACGTCAAATCAGCACGGCCCTTACGTCCGGGGCTACACACGTGTTACAATGGGGGGTACAGAAGGCAGCTACACGGCGACGTGGTGCTAATCCCGAAAGCCTCTCTCAGTTCGGATTGGNGTCTGCAACCCGACTCCATGAAGCTGGATTCGCTAGTAATCGCGCATCAGCCACGGCGCGGNGAATACGTTCCCNGGCCTTGTACACNNCGCCCGTCAGCCATGAAAGCCGGGGGTACCTGAAGTACGTAACCNNNAGNANNNN'
